name: Packaging arbitrage

on:
  workflow_dispatch:
  push:
    branches:
      - "**"


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytest
        pip install pytest-mock
        pip install -r requirements.txt
    - name: Test with pytest
      run: pytest

  build-lib:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install wheel
    - name: Build package
      run: python3 setup.py bdist_wheel

  deploy-on-app-engine:
    needs: [test, build-lib]
    runs-on: ubuntu-latest
    env:
      PUSH_PACKAGES: ${{ github.ref == 'refs/heads/main' && 'main'}}
    steps:
    - name: Initialize Google Cloud SDK
      uses: zxyle/publish-gae-action@master
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        gae_variables: ${{ secrets.GAE_VARIABLES }}

    - name: Publish app to Google App Engine
      run: |
        gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
        gcloud config set project ${{ secrets.PROJECT_ID }}
        gcloud -q app deploy app.yaml --promote

    - name: Test
      run: |
        curl "${{ steps.deploy-on-app-engine.outputs.url }}"





